### ISSUE TITLE
Missing file 'CustomPageCode.cshtml'

### ISSUE THREAD

**Issue by snyhde** [SitecoreSupport/Sitecore.Support.130279#1]
Please provide the file: `/sitecore/shell/client/Speak/Layouts/Renderings/Common/PageCodes/CustomPageCode.cshtml` as it does not exists as part of the package.

The update to the core item now points to the `CustomPageCode.cshtml` file that does not exist.

**Comment by RomanChernyk** [comment]
Hi Mads,

Thank you for reporting this. We will process your feedback.

However, if there are any issues with the patch on your Sitecore instance, please report this via [support portal](https://support.sitecore.net/), check [KB 654910](https://kb.sitecore.net/articles/654910) for details.

This will enable a proper level of SLAs.

**Comment by blipson89** [comment]
@snyhde @RomanChernyk I'm not sure it's missing. I checked out the source code and it looks like this line is at the top:

`[PageVirtualPath("~/sitecore/shell/client/Speak/Layouts/Renderings/Common/PageCodes/CustomPageCode.cshtml"), GeneratedCode("RazorGenerator", "2.0.0.0")]`

I _think_ it means that the Razor Generator creates that file itself and that it doesn't physically exist. If you're having issues, it may mean that the support dll isn't in your bin directory.

**Comment by DmytroBaranov** [comment]
The issue has been fixed in [8.2.0.1](https://github.com/SitecoreSupport/Sitecore.Support.130279/releases/tag/8.2.0.1)
